import { Activity } from './types'

export const activities: Activity[] = [
  {
    slug: 'praia-do-campeche',
    name: 'Praia do Campeche',
    tagline: 'Wild & magical beach with calm shallow waters',
    description:
      'One of Floripa\'s most beloved beaches, Campeche offers calm, crystal-clear waters perfect for young children. The beach is wide and long, with fine white sand and a relaxed atmosphere. Petroglyphs on the rocky headland add a touch of mystery for curious kids.',
    ageRanges: ['0-2', '3-5', '6-8', '9-12'],
    type: 'beach',
    weather: 'sunny',
    budget: 'free',
    zone: 'south',
    location: 'Campeche, South Floripa',
    duration: '2–4 hours',
    price: 'Free',
    stroller: false,
    parking: true,
    food: true,
    bestTime: 'Morning on weekdays to avoid crowds',
    tips: [
      'Arrive early — parking fills up fast on weekends',
      'Bring shade tent as there are few natural shadows',
      'Snack bars open from 10am, fresh coconut water available',
    ],
    warnings: [
      'Can have strong waves in the afternoon',
      'No lifeguard on duty — supervise children closely',
    ],
    kidScore: { safety: 4, fun: 5, access: 3, budget: 5 },
    featured: true,
  },
  {
    slug: 'lagoa-do-peri',
    name: 'Lagoa do Peri',
    tagline: 'Fresh-water lagoon inside a nature park',
    description:
      'A stunning freshwater lagoon surrounded by Atlantic forest, Lagoa do Peri is ideal for families who want to swim without sea waves. The shallow edges are perfect for toddlers. Pedal boats and kayaks are available for rent, and the park has picnic areas with shade.',
    ageRanges: ['0-2', '3-5', '6-8', '9-12'],
    type: 'nature',
    weather: 'sunny',
    budget: 'free',
    zone: 'south',
    location: 'Lagoa do Peri State Park, South Floripa',
    duration: '3–5 hours',
    price: 'Free entry · Pedal boats R$ 25/hr',
    stroller: false,
    parking: true,
    food: true,
    bestTime: 'Weekday mornings for the calmest water',
    tips: [
      'Pack a picnic — the shaded tables are lovely',
      'Water shoes recommended for rocky entry points',
      'Kayak rental is great for ages 6+',
    ],
    warnings: [
      'No lifeguards — water depth varies',
      'Insect repellent strongly recommended in the forest trails',
    ],
    kidScore: { safety: 4, fun: 5, access: 3, budget: 5 },
    featured: true,
  },
  {
    slug: 'praia-de-jurere-internacional',
    name: 'Jurerê Internacional',
    tagline: 'Pristine beach with full family infrastructure',
    description:
      'Jurerê Internacional is Floripa\'s most well-equipped beach — calm, clean, and with excellent facilities. Beach clubs like Café del Mar offer kids\' areas, and the flat calm water is ideal for swimming. The wide promenade is great for bikes and strollers.',
    ageRanges: ['0-2', '3-5', '6-8', '9-12'],
    type: 'beach',
    weather: 'sunny',
    budget: 'paid',
    zone: 'north',
    location: 'Jurerê Internacional, North Floripa',
    duration: 'Half or full day',
    price: 'Beach free · Beach clubs R$ 50–150/person',
    stroller: true,
    parking: true,
    food: true,
    bestTime: 'Mornings for calm water; afternoons for vibe',
    tips: [
      'The promenade is stroller-friendly with flat paths',
      'Several beach clubs have dedicated kids\' pools',
      'Lifeguards on duty every day in summer',
    ],
    warnings: [
      'Beach clubs can be expensive',
      'Gets very busy in January — book beach chairs in advance',
    ],
    kidScore: { safety: 5, fun: 5, access: 5, budget: 2 },
    featured: true,
  },
  {
    slug: 'parque-da-cidade',
    name: 'Parque da Cidade',
    tagline: 'Large urban park with playgrounds and trails',
    description:
      'A sprawling urban park in the south of the island, Parque da Cidade features multiple playgrounds, walking trails, and open grassy areas perfect for picnics. Kids can explore nature while parents relax in the shade. The park has a small lake and exercise equipment.',
    ageRanges: ['0-2', '3-5', '6-8', '9-12'],
    type: 'park',
    weather: 'both',
    budget: 'free',
    zone: 'south',
    location: 'Saco Grande, South-Center Floripa',
    duration: '1–3 hours',
    price: 'Free',
    stroller: true,
    parking: true,
    food: false,
    bestTime: 'Late afternoon for cooler temperatures',
    tips: [
      'Bring your own snacks and water',
      'The playground for toddlers is fenced — great for under-3s',
      'Dogs allowed on leash — great for pet-loving families',
    ],
    warnings: [
      'Some trails are uneven — not suitable for strollers',
      'Bring mosquito repellent in the evening',
    ],
    kidScore: { safety: 5, fun: 4, access: 4, budget: 5 },
    featured: false,
  },
  {
    slug: 'lagoa-da-conceicao',
    name: 'Lagoa da Conceição',
    tagline: 'Windsurfing, food & vibes in the heart of the island',
    description:
      'The iconic Lagoa da Conceição is a brackish lagoon in the center of the island. Perfect for older kids and teens who want to try windsurfing, kitesurfing, or stand-up paddleboarding. The village around the lagoon has great restaurants and an artisan market on weekends.',
    ageRanges: ['6-8', '9-12'],
    type: 'nature',
    weather: 'sunny',
    budget: 'paid',
    zone: 'lagoa',
    location: 'Lagoa da Conceição, Central Floripa',
    duration: '2–4 hours',
    price: 'Paddle board R$ 40/hr · Lessons from R$ 80',
    stroller: false,
    parking: true,
    food: true,
    bestTime: 'Afternoon when wind picks up for water sports',
    tips: [
      'Weekend artisan market is a must-visit',
      'SUP rental is easy and affordable for older kids',
      'Great restaurants lining the shore for lunch',
    ],
    warnings: [
      'Wind can be strong — not ideal for toddlers near the water',
      'Weekend traffic around Lagoa can be heavy',
    ],
    kidScore: { safety: 3, fun: 5, access: 3, budget: 3 },
    featured: false,
  },
  {
    slug: 'beach-park-norte',
    name: 'Praia dos Ingleses',
    tagline: 'Calm family beach with shallow warm water',
    description:
      'One of the calmest beaches in Floripa, Ingleses is a long crescent bay with very shallow, warm water. The beach is lined with barracas (beach bars) with excellent seafood. The calm conditions make it ideal for young children learning to swim or simply playing in the water.',
    ageRanges: ['0-2', '3-5', '6-8', '9-12'],
    type: 'beach',
    weather: 'sunny',
    budget: 'free',
    zone: 'north',
    location: 'Ingleses, North Floripa',
    duration: '2–4 hours',
    price: 'Free',
    stroller: false,
    parking: true,
    food: true,
    bestTime: 'Morning for calm waters before afternoon wind',
    tips: [
      'Water is exceptionally calm — perfect for baby-first-swim',
      'Local barracas serve excellent fresh fish and pastéis',
      'Walk the full length of the beach at low tide',
    ],
    warnings: [
      'Can get crowded in peak summer (Dec–Feb)',
      'Afternoon wind makes it cold — bring a towel',
    ],
    kidScore: { safety: 5, fun: 4, access: 4, budget: 5 },
    featured: false,
  },
  {
    slug: 'floripa-shopping-kids',
    name: 'Floripa Shopping — Kids Zone',
    tagline: 'Indoor fun for rainy days',
    description:
      'When the rain hits, Floripa Shopping is a lifesaver for families. The mall has a dedicated kids\' entertainment zone with rides, a soft-play area for toddlers, and a cinema. There\'s also a food court with family-friendly options and plenty of space for strollers.',
    ageRanges: ['0-2', '3-5', '6-8'],
    type: 'indoor',
    weather: 'rainy',
    budget: 'paid',
    zone: 'north',
    location: 'Continente, North Floripa',
    duration: '2–3 hours',
    price: 'Play area R$ 25–40/child',
    stroller: true,
    parking: true,
    food: true,
    bestTime: 'Weekday mornings for less crowds',
    tips: [
      'Bring socks — most play areas require them',
      'Check the cinema schedule in advance for kids\' films',
      'The food court has a dedicated kid-height counter',
    ],
    warnings: [
      'Very busy on rainy weekends',
      'Play area has age/height limits — check before visiting',
    ],
    kidScore: { safety: 5, fun: 4, access: 5, budget: 3 },
    featured: false,
  },
  {
    slug: 'mercado-publico-floripa',
    name: 'Mercado Público',
    tagline: 'Historic food market with kid-friendly bites',
    description:
      'The historic Mercado Público in the city center is a cultural landmark and foodie paradise. Older children will love exploring the stalls selling local crafts, oysters, and traditional Brazilian snacks. The surrounding square is great for running around after eating.',
    ageRanges: ['3-5', '6-8', '9-12'],
    type: 'restaurant',
    weather: 'rainy',
    budget: 'paid',
    zone: 'center',
    location: 'Centro, Florianópolis',
    duration: '1–2 hours',
    price: 'Budget-friendly — snacks from R$ 5',
    stroller: true,
    parking: false,
    food: true,
    bestTime: 'Lunchtime on weekdays',
    tips: [
      'Try the pastel de camarão (shrimp pastry) — kids love it',
      'The square outside is great for a post-lunch run-around',
      'Combine with a visit to the nearby cathedral',
    ],
    warnings: [
      'Can be very busy at peak lunch hours',
      'Street parking is difficult — use public transport or Uber',
    ],
    kidScore: { safety: 4, fun: 3, access: 4, budget: 4 },
    featured: false,
  },
]

export const activityTypeColors: Record<string, string> = {
  beach: 'from-sky-300 to-blue-400',
  park: 'from-green-300 to-emerald-400',
  nature: 'from-teal-300 to-cyan-400',
  indoor: 'from-violet-300 to-purple-400',
  restaurant: 'from-amber-300 to-orange-400',
  event: 'from-pink-300 to-rose-400',
}

export const activityTypeLabels: Record<string, string> = {
  beach: 'Beach',
  park: 'Park',
  nature: 'Nature',
  indoor: 'Indoor',
  restaurant: 'Restaurant',
  event: 'Event',
}

export const zoneLabels: Record<string, string> = {
  north: 'North',
  south: 'South',
  lagoa: 'Lagoa',
  center: 'Center',
}
